config/routes.rb
Rails.application.routes.draw do
  get "pages/about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "pages#index"
  resources :cards, only: [ :index, :show ]
  resources :card_owners, only: [ :index, :show ]
  get "about", to: "pages#about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :card_type
  has_many :card_ownerships
  has_many :card_owners, through: :card_ownerships

  validates :name, presence: true, uniqueness: true
  validates :desc, presence: true
end

app/models/card_owner.rb
class CardOwner < ApplicationRecord
  has_many :card_ownerships
  has_many :cards, through: :card_ownerships
  #many to many relation ship with cards

  validates :name, presence: true
end

app/models/card_ownership.rb
class CardOwnership < ApplicationRecord
  belongs_to :card
  belongs_to :card_owner
end

app/models/card_type.rb
class CardType < ApplicationRecord
  has_many :cards

  validates :name, presence: true, uniqueness: true
end

app/models/category.rb
class Category < ApplicationRecord
  #one to many relationship with Card
  has_many :cards

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/card_owners_controller.rb
class CardOwnersController < ApplicationController
  def index
    @owners = CardOwner.includes(:cards)
  end

  def show
    @owner = CardOwner.find(params[:id])
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    if params[:query].present? || params[:card_type_id].present?
      # show all cards
      @results = Card.all

      # apply name search
      if params[:query].present?
        @results = @results.where("name LIKE ?", "%#{params[:query]}%")
      end

      # apply type filter
      if params[:card_type_id].present?
        @results = @results.where(card_type_id: params[:card_type_id])
      end

      @results = @results.page(params[:page]).per(25)
      @cards = []
    else

      @cards = Card.limit(200).page(params[:page]).per(25)
      @results = []
    end
  end

  def search
    redirect_to cards_path(query: params[:query], card_type_id: params[:card_type_id])
  end

  def show
    @card = Card.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @cards = Card.all
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/card_owner_helper.rb
module CardOwnerHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/card_owners/index.html.erb
<h1>Players</h1>
<%= render 'layouts/navbar' %>

<% @owners.each do |owner| %>
  <h3><%= link_to owner.name, card_owner_path(owner) %></h3>
<% end %>

app/views/card_owners/show.html.erb
<h1><%= @owner.name %></h1>

<h2>Owned Cards</h2>
<ul>
  <% if @owner.cards.any? %>
    <% @owner.cards.each do |card| %>
      <li><%= link_to card.name, card_path(card) %> (Type: <%= card.card_type.name %>)</li>
    <% end %>
  <% else %>
    <li>No cards owned</li>
  <% end %>
</ul>

app/views/cards/index.html.erb
<h1>Welcome to YugiohAPI</h1>
<%= render 'layouts/navbar' %>

<div id='formDiv'>
  <%= form_with(url: cards_path, method: :get, local: true) do %>
    <div>
      <%= label_tag :query, "Search Cards:" %>
      <%= text_field_tag :query, params[:query], placeholder: "Enter card name" %>
    </div>
    <div>
      <%= label_tag :card_type_id, "Filter by Card Type:" %>
      <%= select_tag :card_type_id, options_from_collection_for_select(CardType.all, :id, :name, params[:card_type_id]), include_blank: "All" %>
    </div>
    <%= submit_tag "Search" %>
  <% end %>
</div>

<h2><%= @results.present? ? "Search Results:" : "First 200 Cards:" %></h2>

<%# conditional check if there is results from search and filter%>
<% if @results.empty? && params[:query].present? %>
  <p>No cards found for "<%= params[:query] %>". Please try a different search.</p>
<% else %>

<%# shows result of search and filter %>
<ul>
  <% if @results.present? %>
    <% @results.each do |card| %>
      <li class="links">
        <%= link_to "#{card.name}, Card ID: #{card.id}, Type: #{card.card_type&.name}", card_path(card) %>
      </li>
    <% end %>
  <% else %>
    <% @cards.each do |card| %>
      <li>
        <%= link_to card.name, card_path(card) %>
      </li>
    <% end %>
  <% end %>
</ul>
<% end %>

<%= paginate @results if @results.present? %>
<%= paginate @cards if @cards.present? %>

app/views/cards/show.html.erb
<h1><%= @card.name %></h1>
<p><strong>Type:</strong> <%= @card.card_type.name %></p>
<p><strong>Description:</strong> <%= @card.desc %></p>
<p><strong>Attack:</strong> <%= @card.atk.present? ? @card.atk : "N/A" %></p>
<p><strong>Defense:</strong> <%= @card.def.present? ? @card.def : "N/A" %></p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'About', about_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Cards', cards_path, class: 'nav-link' %>
      </li>
      <li>
        <%= link_to 'Players', card_owners_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Intro To Rails Imanlupig" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<%= render 'layouts/navbar' %>
<p>
  For this project I will be using data from the YuGiOh API. This API provides information
  about YuGiOh TCG, such card names, type, descriptions. The data structure will display
  card details and I will also be using Faker gem to create users and establish associations
  between the users and some cards.
</p>

<%= image_tag("yugioh_erd_project.drawio.png", alt: "Yu-Gi-Oh API ERD Diagram") %>

<p>
  The Cards and Card Types will be linked by the card_type_id.
  The Owners will connect to the Cards using a join table OwnerCards, allowing each owner to have multiple cards and each card having multiple owners. A many-to-many relationship.
</p>

<h2>Data Source</h2>
<p>Data is sourced from the <a href="https://db.ygoprodeck.com/api/v7/cardinfo.php" target="_blank">Yu-Gi-Oh! API</a>, which provides comprehensive information about Yu-Gi-Oh! cards.</p>

app/views/pages/cards.html.erb
<h1>Welcome to YugiohApp</h1>
<p>Explore the collection of Yu-Gi-Oh! cards below:</p>

<div class="card-list">
  <% @cards.each do |card| %>
    <div class="card">
      <h2><%= card.name %></h2>
      <p><%= card.desc %></p>
      <p><strong>Type:</strong> <%= card.card_type.name %></p>
      <p><strong>Attack:</strong> <%= card.atk %></p>
      <p><strong>Defense:</strong> <%= card.def %></p>
    </div>
  <% end %>
</div>

app/views/pages/index.html.erb
<h1>Home Page</h1>
<header>
  <%= render 'layouts/navbar' %>
</header>

<h2>Welcome to 2024 YUGIOH</h2>